### ISSUE TITLE
Possible to remove the bloat?

### ISSUE THREAD

**Issue by visualcookie** [ezekg/flint#29]
Maybe I'm doing it wrong, but somehow the code that get generates is a bit "bloaty". For example the use of margins could be in just one selector instead of defining it for each one again.

It could just be one parent, that adds the margins to the elements. Maybe that'll work. Don't know the status of that kinda stuff in functions/mixins atm.

**Example input:**
http://sassmeister.com/gist/56031734d005414a2bc3

**Comment by ezekg** [comment]
This could be done, but honestly I think it falls under a micro-optimization. Something like that is not going to impact a site's performance much after being minified+gzipped. I'll keep this open in case I ever get some extra time to work on it. Feel free to issue a pull request.

The only changes that would need to be done (I think) would be in [_calculate.scss](https://github.com/ezekg/flint/blob/master/stylesheets/flint/mixins/lib/_calculate.scss); to check if the default breakpoint's output matches what is being sent to `output()`, and is so it should be skipped.

**Comment by ezekg** [comment]
@visualcookie Alternatively, you can use the [longhand syntax](http://flint.gs/docs/#longhand) to explicitly declare the breakpoints you want to change, taking into account the default breakpoint which won't be wrapped in `@media` queries:

```sass
div
  +_("mobile", 4) // Default breakpoint
  +_("desktop", 2.5)
```

**Comment by ezekg** [comment]
I'm closing this for now, since the above solution works for micro-optimizations like this.
