### ISSUE TITLE
How to install and use Flint

### ISSUE THREAD

**Issue by Madebym** [ezekg/flint#30]
Sorry for the total newbie question, still trying to figure all the bowers, gulps, yeomans, etc !! Life was much easier before :))

I installed Flint with Bower, and then referenced it with `@import "flint"`, but the compiler throws an error.
I tried downloading the master zip file and then by placing the flint folder into my project, again it threw an error.

I have been able to install and use Bourbon and Neat, but I really don't know what to do with Flint.

**Comment by ezekg** [comment]
Can you paste in the error that you're getting?

**Comment by Madebym** [comment]
I am getting this error: 
my-folder/bower_components/flint/stylesheets/flint/functions/lib/_calc-width.scss - error reading values after (	

It was also giving me this error, but this one was easy to fix: 
top-level@import directive must be terminated by ';' @import "lib/support-syntax-bem"

I am using Brackets with Sass extension which uses LibSass as a compiler.

**Comment by visualcookie** [comment]
@Madebym Could be LibSass. Didn't tried the use with Flint and LibSass yet.

Can you see what LibSass version this extension uses?

**Comment by Madebym** [comment]
@visualcookie  It uses LibSass 3.1  

It also has a ruby compiler, I'll try switching to that and see if that changes anything.

**Comment by visualcookie** [comment]
@Madebym Well, for LibSass compatibility you have to wait a bit. LibSass is still not finished and doesn't support all the futures of Ruby Sass. But this will come anytime soon. Maybe it'll already work with LibSass 3.2. There are just some functions in Flint which are not compatible with LibSass.

@HugoGiraudel made a tiny project, which shows off the current state of LibSass. https://sass-compatibility.github.io/

**Comment by HugoGiraudel** [comment]
LibSass 3.2 is almost exactly identical to Ruby Sass. It should work, and latest inconsistency are quite easy to fix.

**Comment by Madebym** [comment]
Ok, thanks guys. This clarifies things a lot !!

**Comment by ezekg** [comment]
@Madebym it looks like this is your issue: http://sass-compatibility.github.io/#ampersand_sassscript – Libsass `3.1` doesn't support the SassScript `&`, which is used _heavily_ within Flint. Update your Libsass and I'm betting it will work. This is what it doesn't like:

```sass
// _calc-width.scss
45: @error "You set context to `#{$context}`, but a parent instance could not be found for `#{nth(&, 1) + '::' + $key}`"
```

Thanks @HugoGiraudel for that awesome site. :+1:

**Comment by Madebym** [comment]
@ezekg  Yes, it was throwing an error for `_calc-width.scss` . I'll update node-sass to a newer version that has LibSass 3.2.2 and hopefully it will be fine then.

p.s. On a side note, I think that it would be beneficial to newbies in Sass(like me) if you included some kind of demo page with various grid options in the documentation. 

Something like this:
http://neat.bourbon.io/examples/
http://www.get-maze.co.uk/maze/

**Comment by jonathanphz** [comment]
Hi - I'm using libsass 3.2.5 and I'm getting the same error on line 45 of _calc-width.scss

Libsass 3.2.5
Flint 2.3.3

**Comment by ezekg** [comment]
I don't use libsass, but are you able to test with the newest version (`3.3`)? I believe that the incompatibilities have been fixed in that version, judging from the closed issues. If not, this is a big in libsass; for some reason it's thinking that `@content` isn't being used within the `calc-width` mixin, but it most definitely is.

Is there anyway that you could create a small repo with your libsass setup so I can do a few test compilations? Are you using Grunt or Gulp?

**Comment by ezekg** [comment]
@Madebym your feedback on the docs are hugely appreciated. Thanks. I am in the process of overhauling and setting up the docs to use SassDoc, so they will be a lot more in depth than they are now. I'm hoping to get that done soon. I'll keep you updated.
