### ISSUE TITLE
Node/Libsass support

### ISSUE THREAD

**Issue by donaldwasserman** [ezekg/flint#31]
I read in https://github.com/ezekg/flint/issues/30 that Flint may be compatible with Node/libsass. 

I'm using nodesass 3.1.2, which has a dependency on libsass 3.2.4.

Has anyone gotten it work?

**Comment by ezekg** [comment]
I'm pretty sure that people are using it with Libsass. Just make sure that you're using at least Libsass 3.2 (it sounds like you already are), and it should be fine. Is it not working for you? If so, can you post your error output?

**Comment by donaldwasserman** [comment]
Thanks for getting back so quickly -- 


```
Running "sass:dist" (sass) task
>> invalid selector after &
>>   Line 45  Column 16  css/flint/functions/lib/_calc-width.scss
```

**Comment by ezekg** [comment]
No problem. Can you post your Sass as well so I can see what you're trying to compile?

**Comment by ezekg** [comment]
It looks like it's a bug in Libsass: http://sassmeister.com/gist/177da44e76e8f7e666d2 (uncomment the line I commented out) – you might want to file an issue over at the [Libsass](https://github.com/sass/libsass) repo if it's not already reported. This issue looks like it might be the same: https://github.com/sass/libsass/issues/1260

Sorry man!

**Comment by donaldwasserman** [comment]
Thanks for getting back to me. I'm trying to move some projects over to nodesass. I was hoping I just had some error on my end.

This is a great project by the way.

**Comment by ezekg** [comment]
Thanks, I'm glad you enjoy it! I'll keep an eye on that Libsass issue and see if there are any work around I can do in the meantime.

**Comment by ezekg** [comment]
@donaldwasserman, @kirillbunin: expect the fix in the next release:https://github.com/sass/libsass/issues/1531#issuecomment-137745021 :+1:

**Comment by donaldwasserman** [comment]
This is awesome! Thanks!
