### ISSUE TITLE
Not compatible with libsass

### ISSUE THREAD

**Issue by kirillbunin** [ezekg/flint#36]
Unfortunatly this lib is not compatible with libsass, not sure if there's much to be done on this subject.

    Message:
    bower_components\flint\stylesheets\flint\functions\lib\_calc-width.scss 45:16  invalid selector after &

**Comment by kirillbunin** [comment]
Shoot first, ask questions later.
I noticed that this issue is repost of #31

**Comment by ezekg** [comment]
Yeah, sorry man. There's nothing that I can do right now, unfortunately. All solutions or workarounds would require breaking compatibility with Ruby Sass.
