### ISSUE TITLE
Libsass/Node-sass Update

### ISSUE THREAD

**Issue by donaldwasserman** [ezekg/flint#38]
Wanted to drop an issue to see if anyone had tried updating to Libsass/node-sass. 

The current node-sass package has libsass 3.3, so I tried to update it. 

I'm getting an error `Mixin "flint-calculate" does not accept a content block.`

Any thoughts on this issue?

**Comment by ezekg** [comment]
Can you reproduce it on [SassMeister](http://sassmeister.com/) (not sure if their libsass is up to date or not), or show me any relevant lines within your Sass file? [The `calculate` mixin _does_ accept `@content` block](https://github.com/ezekg/flint/blob/master/stylesheets/flint/mixins/lib/_calculate.scss#L228), so it's likely that this is another bug in libsass. I'd skim their issue tracker and see if anything related to passing around a `@content` block between mixins has been reported lately.

**Comment by donaldwasserman** [comment]
SassMeister is still on 3.2. 

Here's a relevant issue, [but seems to have the opposite issue here.](https://github.com/sass/libsass/issues?utf8=%E2%9C%93&q=%40content+is%3Aissue+is%3Aopen+)

I'll work on getting a SassMeister together and create a ticket.  This was more an informational item to make sure it wasn't just broken for me.

**Comment by ezekg** [comment]
Thanks for the report. I'll look into it more tonight if I can and make sure it's not anything on my end.

**Comment by ezekg** [comment]
Any update on this? I don't think it's anything on my end. Seems to be a bug in libsass' `@content` directive.

**Comment by donaldwasserman** [comment]
Sorry for the delay in getting back to you on this -- I was on vacation. I'll put together a sassmister or codepen or something and submit a ticket to libsass.

**Comment by ezekg** [comment]
No problemo. Hope you had a good vacation. Let me know if there's anything I can do on my end.
