### ISSUE TITLE
Using flint inside other environments

### ISSUE THREAD

**Issue by Thiggel** [ezekg/flint#39]
Hey everyone!
I've just stumbled upon this ace library and I'm so willing to use it in a project of mine which runs on meteor.js. Is there a way to use just the sass files without the ruby code?

**Comment by ezekg** [comment]
The Ruby code won't be used unless you're running a Ruby environment. You can install Flint with Bower via `bower install flint --save` and then import the main `bower_components/flint/stylesheets/flint` Sass file and you should be good to go. If Bower isn't an option, feel free to clone the repo into a `vendor/` folder and just import that way; `stylesheets/_flint.scss` will include all of Flint's source.

**Comment by Thiggel** [comment]
Thank you very much

**Comment by ezekg** [comment]
No problemo. Glad you like the library. :+1:
